### PR TITLE
Fix range of function to be consistent with documentation

### LINKED ISSUE #294: UniformInt does has wrong range [BUG]
function [RandomInt() ](https://github.com/KavrakiLab/robowflex/blob/master/robowflex_library/src/random.cpp#L34)returns a value in [lower_bound, upper_bound] instead of  [lower_bound, upper_bound) as mentioned [here](https://kavrakilab.github.io/robowflex/namespacerobowflex_1_1RNG.html#aaa1fda5137839d2555722cd3a5ebe3dd). 

It's an easy fix, but the question is, do we fix the documentation or the function?
I propose the function since it works better with vector indexing.

### PR DESCRIPTION
**Pull request by ChamzasKonstantinos**
Fixes #294

### CODE REVIEW

**Comment by ChamzasKonstantinos** [comment]
somethings wrong with dart?
This is the error from the ci
```
Cannot add PPA: 'ppa:~dartsim/ubuntu/ppa'.
ERROR: '~dartsim' user or team does not exist.
```

**Comment by ChamzasKonstantinos** [comment]
> somethings wrong with dart? This is the error from the ci
> 
> ```
> Cannot add PPA: 'ppa:~dartsim/ubuntu/ppa'.
> ERROR: '~dartsim' user or team does not exist.
> ```

Seems it was a random failure, I rerun the ci and seems to build now

**Comment by zkingston** [comment]
Please update `uniformSample` and other places that uniformInt was used to respect the new API.

**Review by zkingston — CHANGES_REQUESTED** [review]
See above comment.

**Comment by ChamzasKonstantinos** [comment]
Good catch, I fixed `uniformSample` and verified its correct behavior with `uniformVec` which samples uniformly from a vector with the following syntax `RNG::uniformVec(vec); `

**Review by zkingston — APPROVED** [review]
LGTM

**Pull request merged**
